@startuml

|user|

start

:タイムラインを表示;

if (検索条件を入力) then (yes)
  :該当todoを表示;
  stop
elseif (ソート条件を入力) then (yes)
  :該当todoを表示;
  stop
elseif (いいねする) then (yes)
  :userのいいねリストに追加される;
  stop
elseif (リプライする) then (yes)
  :該当todoを選択すると、リプライが表示される;
  stop
elseif (リマインドする) then (yes)
  :todo作成者のタイムラインの一番上にtodoが表示される;
  stop
endif

:閲覧終了;

stop

@enduml
