@startuml
title authentication
"ログイン画面\n<https://tweetodo/users/login>" as login -> web_server : ログインする（user_email, user_password）
activate login
activate web_server

web_server -> api_server : リクエスト
activate api_server
api_server --> web_server : レスポンス
database DB
api_server -> DB : データ取得/登録
activate DB
DB --> api_server : データ返却

alt ログイン成功
	web_server --> "ホーム画面\n<https://tweetodo/home>" as home : ホーム画面にリダイレクト
else ログイン失敗
	web_server --> login: 認証失敗のメッセージを表示する
end

participant login order 10
participant home order 20
participant web_server order 30
participant api_server order 40
participant DB order 50

@enduml
