@startuml
title アカウント管理
"top_page\n**/top**" as top -> "home_page\n**/home**" as home : log_in\n**/login**
activate top
home -> server : user_email,user_password
activate server
alt ログイン成功
	server  --> home : return user_id
else ログイン失敗
	server  --> top : return login error message
end

|||
database DB
server -> DB : データ取得/登録
DB  --> server : データ返却

top -> home : sign_up\n**/signup**
home -> server : user_email,user_password
alt 登録成功
	server --> home : return user_id
else 登録失敗
	server --> top : return signup error message
end

@enduml
