@startuml
title Follow管理 
opt /login
    "top_page\n**/top**" as top -> "home_page\n**/home**" as home : user_email,user_password
    activate top
    server  --> home : return user_id
end

|||
database DB
server -> DB : データ取得/登録
DB  --> server : データ返却

activate home
home -> "user_page\n**/user_name**" as user : 画面遷移
activate user
user -> server : 作成(user_id)
server --> user : todo_content
|||
user -> server : 詳細(todo_id)
server --> user : todo_content
|||
user -> server : 削除(todo_id)
server --> user : user_id
|||
user -> server : 編集
server --> user : todo_content

participant top order 10
participant home order 20
participant user order 30
participant server order 40
participant DB order 50

@enduml
